---
micronaut:
    application:
        name: footballmanager

---
mongodb:
    uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/footballmanager"
    cluster:
        maxWaitQueueSize: 5
    connectionPool:
        maxSize: 20